# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: A new Nylo Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.27.0 <4.0.0"
dependencies:
  analyzer: ^6.7.0
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  drop_down_list: ^2.0.0
  flutter:
    sdk: flutter
  flutter_debouncer: ^2.0.0
  flutter_form_builder: ^9.7.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  form_builder_validators: ^11.1.1
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  intl: 0.19.0
  number_text_input_formatter: ^1.0.0+8
  nylo_framework: ^6.2.8
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  scaffold_ui: ^1.1.4
  url_launcher: ^6.3.1
  wolt_modal_sheet: ^0.10.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
  #  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  rename: ^3.0.2

# APP ICON - public/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/app_icon/icon.png"
  remove_alpha_ios: true

# RENAME YOUR PROJECT
# flutter pub run rename setAppName --targets ios,android --value "YourAppName"
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/fonts/
    - public/images/
    - public/app_icon/
    - lang/
    - .env
